import { Lead, Buyer, Communication, User, PropertyType, LeadStatus, BuyerType, InvestmentRange, CommunicationType, CommunicationDirection, CommunicationStatus, UserRole } from '../types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'john.doe@presidentialdigs.com',
    firstName: 'John',
    lastName: 'Doe',
    role: 'manager',
    tenantId: 'tenant-1',
    isActive: true,
    lastLoginAt: new Date('2024-01-15T10:30:00Z'),
    createdAt: new Date('2023-06-01T00:00:00Z'),
    updatedAt: new Date('2024-01-15T10:30:00Z'),
  },
  {
    id: 'user-2',
    email: 'sarah.smith@presidentialdigs.com',
    firstName: 'Sarah',
    lastName: 'Smith',
    role: 'agent',
    tenantId: 'tenant-1',
    isActive: true,
    lastLoginAt: new Date('2024-01-14T16:45:00Z'),
    createdAt: new Date('2023-07-15T00:00:00Z'),
    updatedAt: new Date('2024-01-14T16:45:00Z'),
  },
  {
    id: 'user-3',
    email: 'mike.johnson@presidentialdigs.com',
    firstName: 'Mike',
    lastName: 'Johnson',
    role: 'agent',
    tenantId: 'tenant-1',
    isActive: true,
    lastLoginAt: new Date('2024-01-13T14:20:00Z'),
    createdAt: new Date('2023-08-20T00:00:00Z'),
    updatedAt: new Date('2024-01-13T14:20:00Z'),
  },
  {
    id: 'user-4',
    email: 'admin@presidentialdigs.com',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
    tenantId: 'tenant-1',
    isActive: true,
    lastLoginAt: new Date('2024-01-15T09:00:00Z'),
    createdAt: new Date('2023-01-01T00:00:00Z'),
    updatedAt: new Date('2024-01-15T09:00:00Z'),
  },
];

// Mock Leads
export const mockLeads: Lead[] = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@example.com',
    phone: '(555) 123-4567',
    address: '123 Main Street',
    propertyAddress: '123 Main Street',
    city: 'Austin',
    state: 'TX',
    zipCode: '78701',
    propertyType: 'single_family',
    estimatedValue: 350000,
    status: 'contacted',
    assignedTo: 'user-1',
    notes: 'Interested in purchasing single-family homes in Austin area.',
    source: 'Website',
    company: 'Smith Real Estate',
    score: 85,
    createdAt: new Date('2024-01-15T10:30:00Z'),
    updatedAt: new Date('2024-01-20T14:45:00Z'),
  },
  {
    id: '2',
    firstName: 'Jane',
    lastName: 'Williams',
    email: 'jane.williams@example.com',
    phone: '(555) 234-5678',
    address: '456 Oak Avenue',
    propertyAddress: '456 Oak Avenue',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75201',
    propertyType: 'multi_family',
    estimatedValue: 500000,
    status: 'qualified',
    assignedTo: 'user-2',
    notes: 'Looking for multi-family investment properties in Dallas.',
    source: 'Referral',
    company: 'Williams Investment Group',
    score: 92,
    createdAt: new Date('2024-01-12T09:15:00Z'),
    updatedAt: new Date('2024-01-18T16:20:00Z'),
  },
  {
    id: '3',
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'michael.johnson@example.com',
    phone: '(555) 345-6789',
    address: '789 Pine Street',
    propertyAddress: '789 Pine Street',
    city: 'Houston',
    state: 'TX',
    zipCode: '77001',
    propertyType: 'single_family',
    estimatedValue: 280000,
    status: 'new',
    assignedTo: 'user-1',
    notes: 'First-time homebuyer interested in starter homes.',
    source: 'Social Media',
    company: 'Johnson Family Trust',
    score: 78,
    createdAt: new Date('2024-01-20T11:00:00Z'),
    updatedAt: new Date('2024-01-20T11:00:00Z'),
  },
  {
    id: '4',
    firstName: 'Sarah',
    lastName: 'Davis',
    email: 'sarah.davis@example.com',
    phone: '(555) 456-7890',
    address: '321 Elm Drive',
    propertyAddress: '321 Elm Drive',
    city: 'San Antonio',
    state: 'TX',
    zipCode: '78201',
    propertyType: 'commercial',
    estimatedValue: 750000,
    status: 'converted',
    assignedTo: 'user-3',
    notes: 'Commercial real estate investor with multiple properties.',
    source: 'Cold Call',
    company: 'Davis Commercial Properties',
    score: 95,
    createdAt: new Date('2024-01-10T14:30:00Z'),
    updatedAt: new Date('2024-01-25T10:15:00Z'),
  },
  {
    id: '5',
    firstName: 'Robert',
    lastName: 'Brown',
    email: 'robert.brown@example.com',
    phone: '(555) 567-8901',
    address: '654 Maple Lane',
    propertyAddress: '654 Maple Lane',
    city: 'Austin',
    state: 'TX',
    zipCode: '78702',
    propertyType: 'single_family',
    estimatedValue: 420000,
    status: 'contacted',
    assignedTo: 'user-2',
    notes: 'Looking for investment properties in growing Austin neighborhoods.',
    source: 'Website',
    company: 'Brown Investment LLC',
    score: 88,
    createdAt: new Date('2024-01-14T16:45:00Z'),
    updatedAt: new Date('2024-01-19T12:30:00Z'),
  },
  {
    id: '6',
    firstName: 'Lisa',
    lastName: 'Wilson',
    email: 'lisa.wilson@example.com',
    phone: '(555) 678-9012',
    address: '987 Cedar Court',
    propertyAddress: '987 Cedar Court',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75202',
    propertyType: 'multi_family',
    estimatedValue: 650000,
    status: 'qualified',
    assignedTo: 'user-1',
    notes: 'Experienced investor looking to expand portfolio with multi-family properties.',
    source: 'Referral',
    company: 'Wilson Real Estate Holdings',
    score: 91,
    createdAt: new Date('2024-01-13T08:20:00Z'),
    updatedAt: new Date('2024-01-17T15:10:00Z'),
  },
  {
    id: '7',
    firstName: 'David',
    lastName: 'Miller',
    email: 'david.miller@example.com',
    phone: '(555) 789-0123',
    address: '147 Birch Street',
    propertyAddress: '147 Birch Street',
    city: 'Houston',
    state: 'TX',
    zipCode: '77002',
    propertyType: 'single_family',
    estimatedValue: 320000,
    status: 'new',
    assignedTo: 'user-3',
    notes: 'Young professional looking for first home in Houston area.',
    source: 'Social Media',
    company: 'Miller Family',
    score: 76,
    createdAt: new Date('2024-01-19T13:15:00Z'),
    updatedAt: new Date('2024-01-19T13:15:00Z'),
  },
  {
    id: '8',
    firstName: 'Jennifer',
    lastName: 'Garcia',
    email: 'jennifer.garcia@example.com',
    phone: '(555) 890-1234',
    address: '258 Spruce Avenue',
    propertyAddress: '258 Spruce Avenue',
    city: 'San Antonio',
    state: 'TX',
    zipCode: '78202',
    propertyType: 'land',
    estimatedValue: 150000,
    status: 'lost',
    assignedTo: 'user-2',
    notes: 'Was interested in land development but decided to pursue other opportunities.',
    source: 'Cold Call',
    company: 'Garcia Development Corp',
    score: 65,
    createdAt: new Date('2024-01-11T09:15:00Z'),
    updatedAt: new Date('2024-01-17T14:20:00Z'),
  },
  {
    id: '9',
    firstName: 'Christopher',
    lastName: 'Martinez',
    email: 'christopher.martinez@example.com',
    phone: '(555) 901-2345',
    address: '369 Walnut Drive',
    propertyAddress: '369 Walnut Drive',
    city: 'Austin',
    state: 'TX',
    zipCode: '78703',
    propertyType: 'single_family',
    estimatedValue: 480000,
    status: 'contacted',
    assignedTo: 'user-1',
    notes: 'Looking for luxury single-family homes in premium Austin locations.',
    source: 'Website',
    company: 'Martinez Luxury Homes',
    score: 89,
    createdAt: new Date('2024-01-16T12:00:00Z'),
    updatedAt: new Date('2024-01-21T09:30:00Z'),
  },
  {
    id: '10',
    firstName: 'Amanda',
    lastName: 'Taylor',
    email: 'amanda.taylor@example.com',
    phone: '(555) 012-3456',
    address: '741 Hickory Lane',
    propertyAddress: '741 Hickory Lane',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75203',
    propertyType: 'multi_family',
    estimatedValue: 580000,
    status: 'qualified',
    assignedTo: 'user-1',
    notes: 'Real estate investor looking to exit market. Property has good cash flow but wants to liquidate for other investments.',
    source: 'Referral',
    company: 'Taylor Investment Group',
    score: 89,
    createdAt: new Date('2024-01-11T09:15:00Z'),
    updatedAt: new Date('2024-01-17T14:20:00Z'),
  },
];

// Mock Buyers
export const mockBuyers: Buyer[] = [
  {
    id: 'buyer-1',
    companyName: 'Texas Property Investors LLC',
    contactName: 'Mark Johnson',
    email: 'mark@texaspropertyinvestors.com',
    phone: '(555) 111-2222',
    address: '1000 Investment Blvd',
    city: 'Austin',
    state: 'TX',
    zipCode: '78701',
    buyerType: 'wholesaler',
    investmentRange: '500k-1m',
    preferredPropertyTypes: ['single_family', 'multi_family'],
    preferredLocations: ['Austin', 'Dallas'],
    maxPurchasePrice: 1000000,
    minPurchasePrice: 500000,
    cashAvailable: 750000,
    financingType: 'cash',
    closingTimeframe: '30-45 days',
    isActive: true,
    notes: 'Experienced wholesaler looking for off-market deals in Texas.',
    source: 'Referral',
    assignedTo: 'user-1',
    lastContactDate: new Date('2024-01-15T10:30:00Z'),
    createdAt: new Date('2024-01-10T00:00:00Z'),
    updatedAt: new Date('2024-01-15T10:30:00Z'),
  },
  {
    id: 'buyer-2',
    companyName: 'Dallas Real Estate Group',
    contactName: 'Sarah Williams',
    email: 'sarah@dallasrealestate.com',
    phone: '(555) 222-3333',
    address: '2000 Commerce Street',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75201',
    buyerType: 'investor',
    investmentRange: '1m-2m',
    preferredPropertyTypes: ['multi_family', 'commercial'],
    preferredLocations: ['Dallas', 'Fort Worth'],
    maxPurchasePrice: 2000000,
    minPurchasePrice: 1000000,
    cashAvailable: 1500000,
    financingType: 'cash',
    closingTimeframe: '45-60 days',
    isActive: true,
    notes: 'Large-scale investor focused on multi-family and commercial properties.',
    source: 'Website',
    assignedTo: 'user-2',
    lastContactDate: new Date('2024-01-14T16:45:00Z'),
    createdAt: new Date('2024-01-08T00:00:00Z'),
    updatedAt: new Date('2024-01-14T16:45:00Z'),
  },
  {
    id: 'buyer-3',
    companyName: 'Houston Property Solutions',
    contactName: 'Mike Chen',
    email: 'mike@houstonpropertysolutions.com',
    phone: '(555) 333-4444',
    address: '3000 Main Street',
    city: 'Houston',
    state: 'TX',
    zipCode: '77001',
    buyerType: 'flipper',
    investmentRange: '200k-500k',
    preferredPropertyTypes: ['single_family'],
    preferredLocations: ['Houston', 'Sugar Land'],
    maxPurchasePrice: 500000,
    minPurchasePrice: 200000,
    cashAvailable: 300000,
    financingType: 'hard_money',
    closingTimeframe: '15-30 days',
    isActive: true,
    notes: 'Quick flipper looking for distressed properties in Houston area.',
    source: 'Cold Call',
    assignedTo: 'user-3',
    lastContactDate: new Date('2024-01-13T14:20:00Z'),
    createdAt: new Date('2024-01-05T00:00:00Z'),
    updatedAt: new Date('2024-01-13T14:20:00Z'),
  },
  {
    id: 'buyer-4',
    companyName: 'San Antonio Investment Partners',
    contactName: 'Lisa Rodriguez',
    email: 'lisa@sanantonioinvestment.com',
    phone: '(555) 444-5555',
    address: '4000 Broadway',
    city: 'San Antonio',
    state: 'TX',
    zipCode: '78201',
    buyerType: 'investor',
    investmentRange: '300k-800k',
    preferredPropertyTypes: ['single_family', 'multi_family'],
    preferredLocations: ['San Antonio', 'New Braunfels'],
    maxPurchasePrice: 800000,
    minPurchasePrice: 300000,
    cashAvailable: 600000,
    financingType: 'conventional',
    closingTimeframe: '30-45 days',
    isActive: true,
    notes: 'Long-term investor focused on rental properties in San Antonio.',
    source: 'Referral',
    assignedTo: 'user-1',
    lastContactDate: new Date('2024-01-12T09:15:00Z'),
    createdAt: new Date('2024-01-03T00:00:00Z'),
    updatedAt: new Date('2024-01-12T09:15:00Z'),
  },
  {
    id: 'buyer-5',
    companyName: 'Austin Capital Group',
    contactName: 'David Kim',
    email: 'david@austincapitalgroup.com',
    phone: '(555) 555-6666',
    address: '5000 Congress Avenue',
    city: 'Austin',
    state: 'TX',
    zipCode: '78702',
    buyerType: 'wholesaler',
    investmentRange: '400k-1.5m',
    preferredPropertyTypes: ['single_family', 'multi_family', 'commercial'],
    preferredLocations: ['Austin', 'Round Rock'],
    maxPurchasePrice: 1500000,
    minPurchasePrice: 400000,
    cashAvailable: 1200000,
    financingType: 'cash',
    closingTimeframe: '21-30 days',
    isActive: true,
    notes: 'High-volume wholesaler with strong network in Austin market.',
    source: 'Website',
    assignedTo: 'user-2',
    lastContactDate: new Date('2024-01-11T11:00:00Z'),
    createdAt: new Date('2024-01-01T00:00:00Z'),
    updatedAt: new Date('2024-01-11T11:00:00Z'),
  },
];

// Mock Communications
export const mockCommunications: Communication[] = [
  {
    id: 'comm-1',
    leadId: '1',
    buyerId: 'buyer-1',
    type: 'email',
    direction: 'outbound',
    subject: 'Property Opportunity in Austin',
    content: 'Hi Mark, I have a great single-family property in Austin that might interest you. Let me know if you\'d like to see the details.',
    status: 'sent',
    sentAt: new Date('2024-01-15T10:30:00Z'),
    createdAt: new Date('2024-01-15T10:30:00Z'),
    updatedAt: new Date('2024-01-15T10:30:00Z'),
  },
  {
    id: 'comm-2',
    leadId: '2',
    buyerId: 'buyer-2',
    type: 'phone',
    direction: 'inbound',
    subject: 'Follow-up call',
    content: 'Sarah called to discuss the multi-family property in Dallas. Very interested and wants to schedule a viewing.',
    status: 'completed',
    sentAt: new Date('2024-01-14T16:45:00Z'),
    createdAt: new Date('2024-01-14T16:45:00Z'),
    updatedAt: new Date('2024-01-14T16:45:00Z'),
  },
];

// Mock Property Types
export const mockPropertyTypes: PropertyType[] = [
  { id: 'single_family', name: 'Single Family', description: 'Single family residential properties' },
  { id: 'multi_family', name: 'Multi Family', description: 'Multi-family residential properties' },
  { id: 'commercial', name: 'Commercial', description: 'Commercial real estate properties' },
  { id: 'land', name: 'Land', description: 'Vacant land and lots' },
  { id: 'condo', name: 'Condo', description: 'Condominium units' },
  { id: 'townhouse', name: 'Townhouse', description: 'Townhouse properties' },
];

// Mock Lead Statuses
export const mockLeadStatuses: LeadStatus[] = [
  { id: 'new', name: 'New', description: 'Newly created lead', color: 'blue' },
  { id: 'contacted', name: 'Contacted', description: 'Initial contact made', color: 'yellow' },
  { id: 'qualified', name: 'Qualified', description: 'Lead has been qualified', color: 'green' },
  { id: 'converted', name: 'Converted', description: 'Lead converted to sale', color: 'purple' },
  { id: 'lost', name: 'Lost', description: 'Lead lost or inactive', color: 'red' },
];

// Mock Buyer Types
export const mockBuyerTypes: BuyerType[] = [
  { id: 'wholesaler', name: 'Wholesaler', description: 'Buys and resells properties quickly' },
  { id: 'investor', name: 'Investor', description: 'Long-term property investor' },
  { id: 'flipper', name: 'Flipper', description: 'Buys, renovates, and sells properties' },
  { id: 'end_buyer', name: 'End Buyer', description: 'Final purchaser for personal use' },
];

// Mock Investment Ranges
export const mockInvestmentRanges: InvestmentRange[] = [
  { id: '0-100k', name: '$0 - $100k', min: 0, max: 100000 },
  { id: '100k-250k', name: '$100k - $250k', min: 100000, max: 250000 },
  { id: '250k-500k', name: '$250k - $500k', min: 250000, max: 500000 },
  { id: '500k-1m', name: '$500k - $1M', min: 500000, max: 1000000 },
  { id: '1m-2m', name: '$1M - $2M', min: 1000000, max: 2000000 },
  { id: '2m+', name: '$2M+', min: 2000000, max: null },
];

// Mock Communication Types
export const mockCommunicationTypes: CommunicationType[] = [
  { id: 'email', name: 'Email', description: 'Email communication' },
  { id: 'phone', name: 'Phone', description: 'Phone call' },
  { id: 'text', name: 'Text', description: 'Text message' },
  { id: 'meeting', name: 'Meeting', description: 'In-person meeting' },
  { id: 'video_call', name: 'Video Call', description: 'Video conference call' },
];

// Mock Communication Directions
export const mockCommunicationDirections: CommunicationDirection[] = [
  { id: 'inbound', name: 'Inbound', description: 'Communication received from lead/buyer' },
  { id: 'outbound', name: 'Outbound', description: 'Communication sent to lead/buyer' },
];

// Mock Communication Statuses
export const mockCommunicationStatuses: CommunicationStatus[] = [
  { id: 'pending', name: 'Pending', description: 'Communication pending', color: 'yellow' },
  { id: 'sent', name: 'Sent', description: 'Communication sent', color: 'blue' },
  { id: 'delivered', name: 'Delivered', description: 'Communication delivered', color: 'green' },
  { id: 'completed', name: 'Completed', description: 'Communication completed', color: 'purple' },
  { id: 'failed', name: 'Failed', description: 'Communication failed', color: 'red' },
];

// Mock User Roles
export const mockUserRoles: UserRole[] = [
  { id: 'admin', name: 'Admin', description: 'Full system access', permissions: ['all'] },
  { id: 'manager', name: 'Manager', description: 'Management access', permissions: ['leads', 'buyers', 'reports'] },
  { id: 'agent', name: 'Agent', description: 'Agent access', permissions: ['leads', 'buyers'] },
  { id: 'viewer', name: 'Viewer', description: 'Read-only access', permissions: ['view'] },
];

// Mock Cities
export const mockCities = [
  'Austin', 'Dallas', 'Houston', 'San Antonio', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano', 'Lubbock'
];

// Mock Lead Stages
export const mockLeadStages = [
  { id: 'initial_contact', name: 'Initial Contact', order: 1 },
  { id: 'qualification', name: 'Qualification', order: 2 },
  { id: 'presentation', name: 'Presentation', order: 3 },
  { id: 'negotiation', name: 'Negotiation', order: 4 },
  { id: 'closing', name: 'Closing', order: 5 },
];

// Mock Lead Activities
export const mockLeadActivities = [
  { id: 'call', name: 'Phone Call', type: 'communication' },
  { id: 'email', name: 'Email', type: 'communication' },
  { id: 'meeting', name: 'Meeting', type: 'meeting' },
  { id: 'property_viewing', name: 'Property Viewing', type: 'activity' },
  { id: 'offer_submission', name: 'Offer Submission', type: 'transaction' },
];

// Mock Lead Notes
export const mockLeadNotes = [
  { id: 'note-1', leadId: '1', content: 'Initial contact made via website form', createdAt: new Date('2024-01-15T10:30:00Z') },
  { id: 'note-2', leadId: '1', content: 'Follow-up call scheduled for next week', createdAt: new Date('2024-01-16T14:20:00Z') },
];

// Mock Lead Tasks
export const mockLeadTasks = [
  { id: 'task-1', leadId: '1', title: 'Schedule property viewing', dueDate: new Date('2024-01-20T00:00:00Z'), completed: false },
  { id: 'task-2', leadId: '2', title: 'Send property details', dueDate: new Date('2024-01-18T00:00:00Z'), completed: true },
];

// Mock Lead Documents
export const mockLeadDocuments = [
  { id: 'doc-1', leadId: '1', name: 'Property Photos', type: 'image', url: '/documents/property-photos-1.pdf' },
  { id: 'doc-2', leadId: '2', name: 'Financial Analysis', type: 'pdf', url: '/documents/financial-analysis-2.pdf' },
];

// Mock Lead History
export const mockLeadHistory = [
  { id: 'history-1', leadId: '1', action: 'Created', description: 'Lead created from website form', timestamp: new Date('2024-01-15T10:30:00Z') },
  { id: 'history-2', leadId: '1', action: 'Contacted', description: 'Initial phone call made', timestamp: new Date('2024-01-15T11:00:00Z') },
];

// Mock Lead Analytics
export const mockLeadAnalytics = {
  totalLeads: 10,
  newLeads: 3,
  contactedLeads: 4,
  qualifiedLeads: 2,
  convertedLeads: 1,
  conversionRate: 10,
  averageResponseTime: 2.5,
  topSources: ['Website', 'Referral', 'Social Media'],
  monthlyTrends: [
    { month: 'Jan', leads: 10, conversions: 1 },
    { month: 'Dec', leads: 8, conversions: 2 },
    { month: 'Nov', leads: 12, conversions: 1 },
  ],
};

// Main mock data object
export const mockData = {
  users: mockUsers,
  leads: mockLeads,
  buyers: mockBuyers,
  communications: mockCommunications,
  propertyTypes: mockPropertyTypes,
  leadStatuses: mockLeadStatuses,
  cities: mockCities,
  leadStages: mockLeadStages,
  leadActivities: mockLeadActivities,
  leadNotes: mockLeadNotes,
  leadTasks: mockLeadTasks,
  leadDocuments: mockLeadDocuments,
  leadHistory: mockLeadHistory,
  leadAnalytics: mockLeadAnalytics,
};

export default mockData;