export const PERMISSIONS = {
  // Lead Management
  LEADS_CREATE: 'leads:create',
  LEADS_READ: 'leads:read',
  LEADS_UPDATE: 'leads:update',
  LEADS_DELETE: 'leads:delete',
  LEADS_ASSIGN: 'leads:assign',
  LEADS_EXPORT: 'leads:export',

  // Buyer Management
  BUYERS_CREATE: 'buyers:create',
  BUYERS_READ: 'buyers:read',
  BUYERS_UPDATE: 'buyers:update',
  BUYERS_DELETE: 'buyers:delete',
  BUYERS_ASSIGN: 'buyers:assign',

  // User Management
  USERS_CREATE: 'users:create',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  USERS_ASSIGN_ROLES: 'users:assign_roles',

  // Analytics & Reports
  ANALYTICS_READ: 'analytics:read',
  REPORTS_GENERATE: 'reports:generate',
  REPORTS_EXPORT: 'reports:export',

  // System Administration
  SYSTEM_SETTINGS: 'system:settings',
  SYSTEM_INTEGRATIONS: 'system:integrations',
  SYSTEM_BACKUP: 'system:backup',

  // Communication
  COMMUNICATIONS_SEND: 'communications:send',
  COMMUNICATIONS_READ: 'communications:read',
  COMMUNICATIONS_DELETE: 'communications:delete',

  // Automation
  AUTOMATION_CREATE: 'automation:create',
  AUTOMATION_READ: 'automation:read',
  AUTOMATION_UPDATE: 'automation:update',
  AUTOMATION_DELETE: 'automation:delete',
  AUTOMATION_EXECUTE: 'automation:execute',

  // Tenant Management
  TENANT_CREATE: 'tenant:create',
  TENANT_READ: 'tenant:read',
  TENANT_UPDATE: 'tenant:update',
  TENANT_DELETE: 'tenant:delete',
  TENANT_USER_MANAGE: 'tenant:user_manage',
  TENANT_SETTINGS: 'tenant:settings',
} as const;

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  TENANT_ADMIN: 'TENANT_ADMIN',
  MANAGER: 'MANAGER',
  AGENT: 'AGENT',
  VIEWER: 'VIEWER',
} as const;

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.TENANT_ADMIN]: [
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_UPDATE,
    PERMISSIONS.LEADS_DELETE,
    PERMISSIONS.LEADS_ASSIGN,
    PERMISSIONS.LEADS_EXPORT,
    PERMISSIONS.BUYERS_CREATE,
    PERMISSIONS.BUYERS_READ,
    PERMISSIONS.BUYERS_UPDATE,
    PERMISSIONS.BUYERS_DELETE,
    PERMISSIONS.BUYERS_ASSIGN,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_ASSIGN_ROLES,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.SYSTEM_INTEGRATIONS,
    PERMISSIONS.COMMUNICATIONS_SEND,
    PERMISSIONS.COMMUNICATIONS_READ,
    PERMISSIONS.COMMUNICATIONS_DELETE,
    PERMISSIONS.AUTOMATION_CREATE,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.AUTOMATION_UPDATE,
    PERMISSIONS.AUTOMATION_DELETE,
    PERMISSIONS.AUTOMATION_EXECUTE,
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.TENANT_USER_MANAGE,
    PERMISSIONS.TENANT_SETTINGS,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_UPDATE,
    PERMISSIONS.LEADS_ASSIGN,
    PERMISSIONS.LEADS_EXPORT,
    PERMISSIONS.BUYERS_CREATE,
    PERMISSIONS.BUYERS_READ,
    PERMISSIONS.BUYERS_UPDATE,
    PERMISSIONS.BUYERS_ASSIGN,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.COMMUNICATIONS_SEND,
    PERMISSIONS.COMMUNICATIONS_READ,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.AUTOMATION_EXECUTE,
  ],
  [ROLES.AGENT]: [
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_UPDATE,
    PERMISSIONS.BUYERS_READ,
    PERMISSIONS.BUYERS_UPDATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.COMMUNICATIONS_SEND,
    PERMISSIONS.COMMUNICATIONS_READ,
    PERMISSIONS.AUTOMATION_READ,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.BUYERS_READ,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.COMMUNICATIONS_READ,
    PERMISSIONS.AUTOMATION_READ,
  ],
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
export type Role = typeof ROLES[keyof typeof ROLES]; 