# Secrets Management Configuration
# This file defines the secrets structure and management approach

apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-config
  namespace: dealcycle-crm
data:
  # Secrets Management Strategy
  strategy: "hashicorp-vault"
  
  # Secret Categories
  categories: |
    - database-credentials
    - api-keys
    - jwt-secrets
    - oauth-credentials
    - monitoring-keys
    - backup-keys
  
  # Rotation Schedule
  rotation: |
    database-credentials: 90-days
    api-keys: 180-days
    jwt-secrets: 365-days
    oauth-credentials: 180-days
    monitoring-keys: 365-days
    backup-keys: 90-days

---
# HashiCorp Vault Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: dealcycle-crm
data:
  # Vault Server Configuration
  vault.hcl: |
    storage "file" {
      path = "/vault/data"
    }
    
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    
    api_addr = "http://0.0.0.0:8200"
    cluster_addr = "https://0.0.0.0:8201"
    
    ui = true
    
    # Enable audit logging
    audit "file" {
      file_path = "/vault/logs/audit.log"
    }

---
# Kubernetes Secrets Template
apiVersion: v1
kind: Secret
metadata:
  name: dealcycle-secrets
  namespace: dealcycle-crm
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  mongodb-uri: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9kZWFsY3ljbGU=
  redis-url: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  google-client-id: eW91ci1nb29nbGUtY2xpZW50LWlk
  google-client-secret: eW91ci1nb29nbGUtY2xpZW50LXNlY3JldA==
  twilio-account-sid: eW91ci10d2lsaW8tYWNjb3VudC1zaWQ=
  twilio-auth-token: eW91ci10d2lsaW8tYXV0aC10b2tlbg==
  meilisearch-master-key: eW91ci1tZWlsaXNlYXJjaC1tYXN0ZXIta2V5
  prometheus-admin-password: YWRtaW4=
  grafana-admin-password: YWRtaW4= 