version: '3.8'

services:
  lead-import-service:
    build: .
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/presidential_digs_crm}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - crm-network
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=presidential_digs_crm
    volumes:
      - mongodb_data:/data/db
    networks:
      - crm-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  crm-network:
    driver: bridge
