#!/bin/bash

# Agent 1: Lead Management Specialist Startup Script
# This script starts Agent 1 with specific focus on Story 2.3

echo "🏃 Agent 1: Lead Management Specialist"
echo "======================================"
echo ""
echo "🎯 Mission: Integrate Lead Management with Shared Services"
echo "📋 Story: 2.3 - Integrate Lead Management with Shared Services"
echo "⏰ Timeline: 2-3 days"
echo "🚨 Priority: HIGH (Blocking Epic 2 completion)"
echo ""

echo "📖 Reading Assignment Documentation..."
echo "- Story: docs/stories/2.3.integrate-lead-management-shared-services.md"
echo "- Instructions: docs/agent-assignments/agent-1-lead-management-instructions.md"
echo ""

echo "🔧 Technical Focus Areas:"
echo "1. API Integration: Update lead management API services to use shared useApi hook"
echo "2. State Management: Replace local state with shared useLeads hook"
echo "3. Authentication: Integrate with shared useAuth hook for authentication"
echo "4. Error Handling: Implement shared error boundary and loading patterns"
echo "5. Testing: Comprehensive testing of all lead management features"
echo ""

echo "📁 Key Files to Modify:"
echo "- src/frontend/hooks/services/useLeads.ts"
echo "- src/frontend/pages/leads/index.tsx"
echo "- src/frontend/pages/leads/[id].tsx"
echo "- src/frontend/components/ui/ErrorBoundary.tsx (create)"
echo ""

echo "🎯 Success Criteria:"
echo "- All lead management features work with shared services"
echo "- API integrations use consistent patterns"
echo "- Error handling and loading states work properly"
echo "- Authentication and authorization function correctly"
echo ""

echo "🤝 Coordination Points:"
echo "- May need lead data for Agent 2 (Analytics) integration"
echo "- May need lead triggers for Agent 3 (Automation) workflows"
echo "- May need lead widgets for Agent 4 (Dashboard)"
echo "- Will prepare for Agent 5 (Integration) component consolidation"
echo ""

echo "📚 Shared Resources to Use:"
echo "- Shared component library from Story 1.2"
echo "- Shared hooks (useApi, useAuth, useLeads)"
echo "- Shared utilities (data, error, date, currency, validation)"
echo "- Design system with Chakra UI theme"
echo ""

echo "🚀 Agent 1 is ready to begin implementation!"
echo "Starting work on Story 2.3: Integrate Lead Management with Shared Services"
echo ""
echo "💡 Next Steps:"
echo "1. Read the story documentation thoroughly"
echo "2. Review the existing lead management implementation"
echo "3. Plan the integration with shared services"
echo "4. Begin implementation following the detailed checklist"
echo "5. Commit progress daily with descriptive messages"
echo ""
echo "Good luck, Agent 1! Let's build amazing lead management integration! 🎉" 