apiVersion: v1
kind: Service
metadata:
  name: dealcycle-backend-service
  namespace: dealcycle-crm
  labels:
    app: dealcycle-backend
    environment: production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: dealcycle-backend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800 