apiVersion: v1
kind: Service
metadata:
  name: dealcycle-frontend-service
  namespace: dealcycle-crm
  labels:
    app: dealcycle-frontend
    environment: production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: dealcycle-frontend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800 